### PR TITLE
Update go-encrypt import path for custom url

### PR DESCRIPTION
**Pull request by bufdev**

### CODE REVIEW

**Comment by bufdev** [comment]
ping @ryanskidmore

**Comment by ryanskidmore** [comment]
Hi again Peter,

Sorry for leaving this so long, completely forgot about it! I think it might be best (in my opinion) if all of the import URLs remain as github.com purely so if your domain goes down for whatever reason, the package is not affected - exception is for gopkg.in, since that is fairly established.

Hope this is okay.

**Comment by bufdev** [comment]
It isn't an option - right now, I don't believe your code will compile from
scratch. You have to do the custom url

**Comment by ryanskidmore** [comment]
Eh, whatever. I don't quite agree with that but w/e

**Comment by bufdev** [comment]
No as in its part of the golang spec, lol :) custom urls aren't optional.

**Comment by ryanskidmore** [comment]
I know, but I mean putting it on a custom URL as opposed to just a github url

**Pull request merged**
