### PR TITLE
Use go-encrypt for AES

### PR DESCRIPTION
**Pull request by bufdev**
Hey man,

Welcome to the golang community :) I thought I'd send this along, I did this work for other projects and thought it'd make things simpler. You should probably take what I've done here and make it more idiomatic for your use case, along with allowing different length keys...or just don't merge this at all, haha. But thought you might want to check it out.

### CODE REVIEW

**Comment by ryanskidmore** [comment]
Hi Peter,

Thanks for the PR! One thing that stands out is that the secret is randomly generated - whilst this in theory is a good idea, the secret on the work server and worker need to be the same and this acts as a form of authentication. Forcing the user to somehow transfer the secret to "legal" workers seems a bit too complicated for the average use case. If you modify your PR to use a predefined secret instead of a randomly generated one then i'll pull it in :)

**Comment by bufdev** [comment]
Yep, that is true - how I envision this being used is that on a separate call, you generate a secret, and then later you run with it, something along the lines of (assuming you put `main.go` in `cmd/gowork`):

```
gowork generate > ~/.gowork.secret
gowork run --secret-path ~/.gowork.secret
```

Using the `rand` package means in practice, when people share this secret, it's less likely to be something like `abcd1234`. What do you think?

**Comment by bufdev** [comment]
`s/abcd1234/somethingthatis32charactersbutequallyobvious/`

**Comment by bufdev** [comment]
Alternatively, see the last commit, you can do either now haha.

**Comment by ryanskidmore** [comment]
Good idea, will take a look later :)

**Comment by ryanskidmore** [comment]
Thanks for updating the PR to the latest codebase, have you tested that your changes work?

**Comment by bufdev** [comment]
How should I test it/are there tests available?

**Comment by bufdev** [comment]
If tests are added and/or something as simple as scripted integration
testing is provided, I'd be happy to make sure this complies, but I saw no
tests here so assumed this was in very early alpha stages? :)

**Comment by ryanskidmore** [comment]
My current method of testing is just building a sample application and seeing if it works (until I add tests!). I've got a sample application i'm building at the moment but it's not really complete, pushed it up to the repo anyway (feel free to PR the sample application too if you need to change anything etc!). The client should output a UUIDv4 if everything worked well (this only tests worker registration, but that's appropriate for this PR).

Cheers

**Comment by ryanskidmore** [comment]
Hi Peter - could you merge your branch with the latest changes?

Cheers

**Comment by bufdev** [comment]
OK, updated with the `mustNewTransformer` function, and removed `crypto_test.go`

**Comment by ryanskidmore** [comment]
Merged, cheers!

**Comment by bufdev** [comment]
:)

**Pull request merged**
